services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager-db
    restart: always
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 20s

  app:
    build: .
    container_name: mvc-taskmanager
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=TaskManagerDb;User Id=sa;Password=${SA_PASSWORD}; TrustServerCertificate=True;"
    ports:
      - "8080:8080"

volumes:
  sqlserver-data:
env_file:
  - .env