services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager-db
    restart: always
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  app:
    build: .
    container_name: mvc-taskmanager
    depends_on:
      - db
    env_file:
    - .env
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=TaskManagerDb;User Id=sa;Password=${SA_PASSWORD}; TrustServerCertificate=True;
    ports:
      - "8080:8080"

  ef-migrations:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/bash", "-c", "dotnet tool install dotnet-ef && dotnet ef database update"]
    depends_on:
      - db
    env_file:
    - .env
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=TaskManagerDb;User Id=sa;Password=${SA_PASSWORD}; TrustServerCertificate=True;

volumes:
  sqlserver-data:
